### ISSUE TITLE
Windows Build?

### ISSUE THREAD

**Issue by korewatori** [moeenn/imx-downloader#1]
Just wondering whether you have any plans for either including a windows build or making it so it's compilable on windows. 
I get 
```
[ 11%] Building CXX object CMakeFiles/imx.dir/src/main.cpp.o
In file included from /cygdrive/c/Users/Tori/Downloads/imx-downloader-main/src/main.cpp:3:
/cygdrive/c/Users/Tori/Downloads/imx-downloader-main/src/./Downloader.hpp:5:10: fatal error: curl/curl.h: No such file or directory
    5 | #include <curl/curl.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/imx.dir/build.make:76: CMakeFiles/imx.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/imx.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```
when I try to compile on windows. going to try compiling on linux later

**Comment by moeenn** [comment]
Unfortunately I have only used it on Linux (there it should compile fine). I don't have much experience writing cross-platform C++ applications so porting it to windows is not on the books right now.

**Comment by korewatori** [comment]
That's fair, thanks for the reply though.
